# Generated by Django 2.2.7 on 2020-02-09 09:57

import django.core.validators
from django.db import migrations, models
import schedule.modules.upload_files_helpers
import schedule.modules.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=80)),
                ('building', models.CharField(max_length=20)),
                ('additional', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size])),
                ('route_photo', models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size])),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:                     '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social', models.URLField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
