# Generated by Django 3.0.6 on 2020-07-22 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200210_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.                  Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
