# Generated by Django 2.2.7 on 2020-01-28 10:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schedule.modules.schedule
import schedule.modules.upload_files_helpers
import schedule.modules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='repeat',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='classes',
            name='repeat_until',
            field=models.DateField(blank=True, default=schedule.modules.schedule.date_4months, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Subjects'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size]),
        ),
    ]
