# Generated by Django 2.2.7 on 2020-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200128_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='delete_ID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
