# Generated by Django 2.2.7 on 2020-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_classes_delete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
