# Generated by Django 2.2.7 on 2020-02-06 15:05

from django.db import migrations, models
import schedule.modules.upload_files_helpers
import schedule.modules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200204_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='photo_small',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path_small, validators=[schedule.modules.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='subjects',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path_thumbnail, validators=[schedule.modules.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='teachers',
            name='photo_small',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path_small, validators=[schedule.modules.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='teachers',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=schedule.modules.upload_files_helpers.get_upload_path_thumbnail, validators=[schedule.modules.validators.validate_file_size]),
        ),
    ]
