# Generated by Django 2.2.7 on 2020-02-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200209_1136'),
        ('schedule', '0005_auto_20200206_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.Location'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Teachers'),
        ),
    ]
