# Generated by Django 2.2.7 on 2020-02-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200209_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='location',
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Teachers'),
        ),
    ]
