# Generated by Django 2.2.7 on 2020-02-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200210_1928'),
        ('schedule', '0007_auto_20200210_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.Location'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Teachers'),
        ),
    ]
