# Generated by Django 2.2.7 on 2020-01-28 10:09

from django.db import migrations, models
import schedule.modules.upload_files_helpers
import schedule.modules.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.CharField(blank=True, max_length=2200, null=True)),
                ('photo', models.ImageField(upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size])),
                ('importance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
