# Generated by Django 3.0.6 on 2020-07-22 17:45

from django.db import migrations, models
import schedule.modules.upload_files_helpers
import schedule.modules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20200216_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(help_text='Max 4MB!', upload_to=schedule.modules.upload_files_helpers.get_upload_path, validators=[schedule.modules.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=models.CharField(blank=True, help_text='Max 2200 charecters!', max_length=2200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, help_text='Max 250 charecters!', max_length=250),
        ),
    ]
